import { useState } from "react";
import { Badge, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, List, ListItemButton, ListItemText, Stack, Typography } from "@mui/material";
import { CloseRounded, HomeWorkRounded, MarkEmailUnreadRounded } from "@mui/icons-material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { enqueueSnackbar } from "notistack";
import { api } from "../api/client";

type JoinRequest = { id: number; full_name: string; email: string; phone?: string | null; date_of_birth: string; building_name: string; flat_number: string; created_at: string };
export default function AdminJoinInbox() {
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<JoinRequest | null>(null); const qc = useQueryClient();
  const requests = useQuery({ queryKey: ["join-requests"], queryFn: async () => (await api.get<JoinRequest[]>("/admin/join-requests")).data, refetchInterval: 30_000 });
  const review = useMutation({ mutationFn: async ({ id, decision }: { id: number; decision: "approve" | "reject" }) => api.post(`/admin/join-requests/${id}/${decision}`), onSuccess: async (_data, variables) => { enqueueSnackbar(variables.decision === "approve" ? "Member approved and linked to their flat" : "Request rejected", { variant: "success" }); setSelected(null); await qc.invalidateQueries({ queryKey: ["join-requests"] }); }, onError: (error: any) => enqueueSnackbar(error?.response?.data?.detail || "Request could not be reviewed", { variant: "error" }) });
  const rows = requests.data ?? [];
  return <><IconButton aria-label={`Membership inbox, ${rows.length} pending`} onClick={() => setOpen(true)}><Badge badgeContent={rows.length} color="error"><MarkEmailUnreadRounded /></Badge></IconButton><Dialog open={open} onClose={() => { setOpen(false); setSelected(null); }} fullWidth maxWidth="sm"><DialogTitle><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h5">Membership inbox</Typography><Typography variant="body2" color="text.secondary">Verify identity and household before approving access.</Typography></Box><IconButton onClick={() => setOpen(false)}><CloseRounded /></IconButton></Stack></DialogTitle><DialogContent dividers>{selected ? <Stack spacing={2}><Typography variant="overline" color="primary" fontWeight={900}>APPLICANT DETAILS</Typography><PaperLocation request={selected} /><Detail label="Full name" value={selected.full_name} /><Detail label="Date of birth" value={new Date(`${selected.date_of_birth}T00:00:00`).toLocaleDateString()} /><Detail label="Email" value={selected.email} /><Detail label="Phone" value={selected.phone || "Not provided"} /><Detail label="Requested" value={new Date(selected.created_at).toLocaleString()} /><Typography variant="body2" color="text.secondary">The password is securely stored and never shown here.</Typography></Stack> : <List disablePadding>{requests.isLoading ? <Typography color="text.secondary">Loading requests…</Typography> : rows.length ? rows.map((request) => <ListItemButton key={request.id} onClick={() => setSelected(request)} sx={{ border: 1, borderColor: "divider", borderRadius: 2, mb: 1 }}><ListItemText primary={request.full_name} secondary={`${request.building_name} · Flat ${request.flat_number} · ${request.email}`} /><Typography color="primary" fontWeight={850}>Review</Typography></ListItemButton>) : <Box sx={{ py: 6, textAlign: "center" }}><MarkEmailUnreadRounded sx={{ fontSize: 48, color: "text.disabled" }} /><Typography variant="h6">No pending requests</Typography><Typography color="text.secondary">New applications will appear here.</Typography></Box>}</List>}</DialogContent>{selected && <DialogActions><Button color="error" disabled={review.isPending} onClick={() => review.mutate({ id: selected.id, decision: "reject" })}>Reject</Button><Button variant="contained" disabled={review.isPending} onClick={() => review.mutate({ id: selected.id, decision: "approve" })}>Approve and link flat</Button></DialogActions>}</Dialog></>;
}
function PaperLocation({ request }: { request: JoinRequest }) { return <Box sx={{ p: 2, borderRadius: 2, bgcolor: "action.hover" }}><Stack direction="row" spacing={1.5}><HomeWorkRounded color="primary" /><Box><Typography variant="caption" color="text.secondary">REQUESTED HOUSEHOLD</Typography><Typography fontWeight={900}>{request.building_name} · Flat {request.flat_number}</Typography></Box></Stack></Box>; }
function Detail({ label, value }: { label: string; value: string }) { return <Box><Typography variant="caption" color="text.secondary" fontWeight={800}>{label.toUpperCase()}</Typography><Typography>{value}</Typography><Divider sx={{ mt: 1 }} /></Box>; }
