import { useState } from "react";
import { Badge, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, List, ListItemButton, ListItemText, Stack, Typography } from "@mui/material";
import { CloseRounded, MarkEmailUnreadRounded } from "@mui/icons-material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { enqueueSnackbar } from "notistack";
import { api } from "../api/client";

type JoinRequest = { id: number; full_name: string; email: string; phone?: string | null; date_of_birth: string; created_at: string };

export default function AdminJoinInbox() {
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<JoinRequest | null>(null); const qc = useQueryClient();
  const requests = useQuery({ queryKey: ["join-requests"], queryFn: async () => (await api.get<JoinRequest[]>("/admin/join-requests")).data, refetchInterval: 30_000 });
  const review = useMutation({ mutationFn: async ({ id, decision }: { id: number; decision: "approve" | "reject" }) => api.post(`/admin/join-requests/${id}/${decision}`), onSuccess: (_d, variables) => { enqueueSnackbar(variables.decision === "approve" ? "Member approved" : "Request rejected", { variant: "success" }); setSelected(null); qc.invalidateQueries({ queryKey: ["join-requests"] }); }, onError: (e: any) => enqueueSnackbar(e?.response?.data?.detail || "Could not review request", { variant: "error" }) });
  const rows = requests.data ?? [];
  return <><IconButton aria-label={`Membership inbox, ${rows.length} pending`} onClick={() => setOpen(true)}><Badge badgeContent={rows.length} color="error"><MarkEmailUnreadRounded /></Badge></IconButton><Dialog open={open} onClose={() => { setOpen(false); setSelected(null); }} fullWidth maxWidth="sm"><DialogTitle sx={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><Box><Typography variant="h5">Membership inbox</Typography><Typography variant="body2" color="text.secondary">Review requests from people asking to join your society.</Typography></Box><IconButton onClick={() => setOpen(false)}><CloseRounded /></IconButton></DialogTitle><DialogContent dividers>{selected ? <Stack spacing={2.5}><Typography variant="overline" color="primary" fontWeight={900}>APPLICANT DETAILS</Typography><Detail label="Full name" value={selected.full_name} /><Detail label="Date of birth" value={new Date(`${selected.date_of_birth}T00:00:00`).toLocaleDateString()} /><Detail label="Email" value={selected.email} /><Detail label="Phone" value={selected.phone || "Not provided"} /><Detail label="Requested" value={new Date(selected.created_at).toLocaleString()} /><Typography variant="body2" color="text.secondary">Their password is securely stored and is never shown here.</Typography></Stack> : <List disablePadding>{requests.isLoading ? <Typography color="text.secondary">Loading requests…</Typography> : rows.length ? rows.map((request) => <ListItemButton key={request.id} onClick={() => setSelected(request)} sx={{ borderRadius: 2, mb: 1, border: "1px solid", borderColor: "divider" }}><ListItemText primary={request.full_name} secondary={`${request.email} · Requested ${new Date(request.created_at).toLocaleDateString()}`} /><Typography color="primary" fontWeight={800}>Review</Typography></ListItemButton>) : <Box sx={{ py: 5, textAlign: "center" }}><MarkEmailUnreadRounded sx={{ fontSize: 44, color: "text.secondary" }} /><Typography variant="h6" sx={{ mt: 1 }}>No pending requests</Typography><Typography color="text.secondary">New membership applications will appear here.</Typography></Box>}</List>}</DialogContent>{selected && <DialogActions sx={{ p: 2.5 }}><Button color="error" onClick={() => review.mutate({ id: selected.id, decision: "reject" })} disabled={review.isPending}>Reject</Button><Button variant="contained" onClick={() => review.mutate({ id: selected.id, decision: "approve" })} disabled={review.isPending}>Approve member</Button></DialogActions>}</Dialog></>;
}
function Detail({ label, value }: { label: string; value: string }) { return <Box><Typography variant="caption" color="text.secondary" fontWeight={800}>{label.toUpperCase()}</Typography><Typography>{value}</Typography><Divider sx={{ mt: 1.25 }} /></Box>; }
